### ISSUE TITLE
Scan gets stuck for some organizations

### ISSUE THREAD

**Issue by KarahanGuner** [punk-security/secret-magpie-cli#50]
Scan gets stuck for some organizations:

![stuck](https://user-images.githubusercontent.com/59062880/212305269-30e26293-5829-4838-99e3-7d5436c6d99f.png)

It doesnt log anything.

When I cancel it shows this error:
```
kali@kali:~$ sudo docker run punksecurity/secret-magpie github --org gravitational --pat [githubtoken]
^CTraceback (most recent call last):
          ____              __   _____                      _ __       
         / __ \__  ______  / /__/ ___/___  _______  _______(_) /___  __
        / /_/ / / / / __ \/ //_/\__ \/ _ \/ ___/ / / / ___/ / __/ / / /
       / ____/ /_/ / / / / ,<  ___/ /  __/ /__/ /_/ / /  / / /_/ /_/ / 
      /_/    \__,_/_/ /_/_/|_|/____/\___/\___/\__,_/_/  /_/\__/\__, /  
                                             PRESENTS         /____/  
                              Secret-Magpie ✨

      Scan all your github/bitbucket repos from one tool, with multiple tools!
        
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 856, in next
    item = self._items.popleft()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/main.py", line 52, in <module>
    for result_batch in results:
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 861, in next
    self._cond.wait(timeout)
  File "/usr/local/lib/python3.10/threading.py", line 320, in wait
    waiter.acquire()
KeyboardInterrupt

```

**Comment by SimonGurney** [comment]
Hmmm... not sure why you don't instantly see the banner. Can you run it with "-t" on the docker args and see if you get the banner immediately?

**Comment by SimonGurney** [comment]
I can reproduce this.  I think the first repo it scans is just huge, but I'm checking.

For now, increase the number of parallel repos being scanned

```
--parallel=4
```

**Comment by KarahanGuner** [comment]
> Hmmm... not sure why you don't instantly see the banner. Can you run it with "-t" on the docker args and see if you get the banner immediately?

This shows the banner, but it still doesnt work.

**Comment by KarahanGuner** [comment]
> I can reproduce this. I think the first repo it scans is just huge, but I'm checking.
> 
> For now, increase the number of parallel repos being scanned
> 
> ```
> --parallel=4
> ```

This seems to work.

**Comment by SimonGurney** [comment]
Yup that first repo on that org has 2000 branches!

**Comment by SimonGurney** [comment]
We'll add a branch count limit :)

**Comment by KarahanGuner** [comment]
I just checked and this ```IndexError: pop from an empty deque``` problem still exists.

**Comment by SimonGurney** [comment]
Hi Karahan,

I've had a look through the issues and can't see this one.  Do you have the console output and which org you are scanning?  We will try and reproduce here.

The latest version was only pushed 10 minutes or so ago so the docker image might be still being built.  Can you pull and retry?

**Comment by SimonGurney** [comment]
Ah I see your error above.

Yes so that's always going to be a thing.  When you quit secret magpie early with ctrl-c it kills the background processes and you see this error.  We should try and handle it better really, but it's essentially just the tool quitting in a noisy way.

What you are seeing is not an error.  The issue with getting stuck on a large repo is now fixed, as we scan the 20 newest branches by default, not the 2000 you were seeing on that org.

Obviously running repos in parallel also helps, as one big repo may take hours but smaller ones are being scanned at the same time.

I'm happy this one is closed, are you?

**Comment by KarahanGuner** [comment]
Well the main problem is it getting stuck. When I used the command below it gets stuck in the beginning and doesnt log anything:
```sudo docker run punksecurity/secret-magpie github --org tronprotocol --pat [githubtoken]```
When I try it with ```--parallel=4``` option it gets stuck in repository 30. 
I also tried to increase the max branch count to 1000, but it got stuck at the beginning.

**Comment by SimonGurney** [comment]
Yeah so it's not stuck, it's just taking a long time to process the bigger repos and it looks stuck.

Because we scan multiple repos at the same time, we cant accept a ctrl c and skip that repo as it might be doing 4 others etc.

You can use single branch mode and that will only scan the default branch, or set the max branch count to a low number like 5.

Trufflehog is way slower than gitleaks, so you could also disable trufflehog and just use gitleaks.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by KarahanGuner** [comment]
Thanks for clarifying, I'm gonna let it run for a while with the default settings.

**Comment by SimonGurney** [comment]
Sounds good.  I've opened #56 and #57 to ensure some fixes make it in to tidy up the output a little.

We really appreciate all the feedback you've given.  Let me know if you us to send out some stickers :)

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by KarahanGuner** [comment]
Thank you for all the work your team has been putting in and making this tool public. I'll keep opening new issues if I see a bug or  have a good idea for the project.
